import type { GamePack } from '../pack.js';
import { diceSet } from '../components.js';
import { handZones, MAX_SEATS } from './common.js';

/**
 * Dice tray for tabletop RPGs. Rolls are generated by the server's CSPRNG and are not
 * re-rollable by the client, so nobody can fudge a result by refreshing.
 */
export const dicePack: GamePack = {
  manifest: {
    formatVersion: 1,
    id: 'dice',
    name: 'Dice Tray',
    author: 'built-in',
    description: 'A full polyhedral set. Server-rolled, so results are honest. Drag dice out, tap to roll, gather them back into the tray.',
    minSeats: 1,
    maxSeats: MAX_SEATS,
    defaultEnforcement: 'off',
    tableColor: '#3b2f4a',
  },
  components: diceSet([4, 6, 8, 10, 12, 20, 100]),
  zones: [
    ...handZones(MAX_SEATS),
    { id: 'tray', label: 'Dice tray', ownerSeat: null, visibility: 'public', x: 0, z: 0, w: 5, h: 3, layout: 'free' },
  ],
  setup: [
    { componentIds: ['repeat:d20:2', 'repeat:d6:6', 'd4', 'd8', 'd10', 'd12', 'd100'], as: 'loose', zoneId: 'tray', x: 0, z: 0, faceUp: true, shuffled: false },
  ],
};
